crm/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^crm/', include('crmsite.urls', namespace='crmsite')),
    url(r'^admin/', include(admin.site.urls)),
]

crmsite/urls.py
from django.conf.urls import patterns, url
from crmsite.views import companies_view, users_view, company_create_or_update, company_save, company_details, change_user_status, create_edit_user, save_user

urlpatterns = patterns('',
                       url(r'^$', companies_view, name='companies'),
                       # AUTHORIZATION
                       url(r'^logout/$', 'django.contrib.auth.views.logout', {
                           'template_name': 'registration/logout.html'}),
                       url(r'^perm_login/$', 'django.contrib.auth.views.login', {
                           'template_name': 'registration/missing_permission.html'}),
                       #USER
                       url(r'^users/$', users_view, name='users'),
                       url(r'^user/add/$', create_edit_user, name='create_edit_user'),
                       url(r'^user/save/$', save_user, name='save_user'),
                       url(r'^user/(?P<pk>\d+)/changestatus/$', change_user_status, name='change_user_status'),
                       #COMPANY
                       url(r'^company/add/$', company_create_or_update, name='company_create_or_update'),
                       url(r'^create_company/$', company_save, name='company_save'),
                       url(r'^create_company/(\d+)/$', company_save, name='company_update'),
                       url(r'^company/(?P<pk>\d+)/$', company_details, name='company_details')
                       )

crmsite/models.py
from django.db import models
from django.core.validators import MinValueValidator


class Company(models.Model):
    name = models.CharField(max_length=100, unique=True)
    street = models.CharField(max_length=50)
    house_number = models.IntegerField(blank=False, validators=[MinValueValidator(1)])
    apartment_number = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(1)])
    postal_code = models.CharField(max_length=6)
    city = models.CharField(max_length=100)

    def __str__(self):
        return self.name

crmsite/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from crmsite.models import Company
from django.contrib.auth.models import User

@login_required
def companies_view(request):
    template_name = 'site/lists/companies.html'
    companies = Company.objects.all()
    return render(request, template_name, {'companies': companies})


@login_required
def company_create_or_update(request, pk=''):
    template_name = 'site/forms/company_form.html'
    if pk:
        company = Company.objects.get(id=pk)
    else:
        company = ''
    return render(request, template_name, {'company': company})


@login_required
def company_details(request, pk):
    template_name = 'site/details/company.html'
    company = Company.objects.get(id=pk)
    return render(request, template_name, {'company': company})

@login_required
def company_save(request, pk=''):
    p = request.POST
    print(p)
    company = Company.objects.get(id=pk) if pk != '' else Company.objects.create(house_number=int(p['house_number']))
    company.name = p['name']
    company.street = p['street']
    print("House number form: " + p['house_number'])
    # company.house_number = int(p['house_number'])
    if p['apartment_number'] != '':
        company.apartment_number = int(p['apartment_number'])
    company.postal_code = p['postal_code']
    company.city = p['city']
    company.save()

    if pk == '':
        pk = company.id

    return HttpResponseRedirect(reverse('crmsite:company_details', args=[pk]))


@login_required
def users_view(request):
    template_name = 'site/lists/users.html'
    users = User.objects.all()
    return render(request, template_name, {'users': users})


@login_required
def change_user_status(request, pk):
    user = User.objects.get(id=pk)
    user.is_active = not user.is_active
    user.save()
    return HttpResponseRedirect(reverse('crmsite:users', args=[]))


@login_required
def create_edit_user(request):
    template_name = 'site/forms/user_form.html'
    return render(request, template_name, {})

@login_required
def save_user(request):
    p = request.POST
    user = User.objects.create_user(username=p['username'], email=None, password=p['password'], first_name=p['first_name'], last_name=p['last_name'])
    return HttpResponseRedirect(reverse('crmsite:users', args=[]))

crmsite/templates/site/details/company.html
{% extends "site/template.html" %}
{% block title %}Company details{% endblock %}
{% block content %}
  <div class="object-title">
    <div>
      <h2>Company: {{ company.name }}</h2>
    </div>
  </div>
  <div class="custom_form">
    <div><b>Street:</b><br>{{ company.street }}</div>
    <div><b>House number:</b><br>{{ company.house_number }}</div>
    {% if company.apartment_number %}
      <div><b>Apartment number:</b><br>{{ company.apartment_number }}</div>
    {% endif %}
    <div><b>PostalCode:</b><br>{{ company.postal_code }}</div>
    <div><b>City:</b><br>{{ company.city }}</div>
  </div>
{% endblock %}

crmsite/templates/site/forms/company_form.html
{% extends "site/template.html" %}
{% block title %}Add/Edit Company{% endblock %}
{% block content %}
  <div class="custom_form">
    {%  if  company %}
      <h3>Update Company</h3>
      <form action="{% url 'rtpm:company_update' company.id %}" method="post">
        {% csrf_token %}
        <div>
          <div class="title-status">
            <span>
              <label for="id_name" class="w150">Name: </label>
              <input id="id_name" name="name" maxlength="100" type="text" value="company.name" autofocus required>
            </span><br><br>
            <span>
              <label for="id_street" class="w150">Street:</label>
              <input id="id_street" name="street" type="text" value="company.street" required>
            </span><br><br>
            <span>
              <label for="id_house_number" class="w150">House number:</label>
              <input id="id_house_number" name="house_number" type="number" value="company.house_number" required>
            </span><br><br>
            <span>
              <label for="id_apartment_number" class="w150">Apartment number:</label>
              <input id="id_apartment_number" name="apartment_number" value="company.apartment_number" type="number">
            </span><br><br>
            <span>
              <label for="id_postal_code" class="w150">Postal code:</label>
              <input id="id_postal_code" name="postal_code" type="text" pattern="[0-9]{2}\-[0-9]{3}" value="company.postal_code" required>
            </span><br><br>
            <span>
              <label for="id_city" class="w150">City:</label>
              <input id="id_city" name="city" type="text" value="company.city" required>
            </span><br><br>
          </div>
        </div>
        <button class="button form-button" type="submit">Update</button>
    {% else %}
      <h3>Add new Company</h3>
      <form action="{% url 'crmsite:company_save' %}" method="post">
        {% csrf_token %}
        <div>
          <div class="title-status">
            <span>
              <label for="id_name" class="w150">Name: </label>
              <input id="id_name" name="name" maxlength="100" type="text" autofocus required>
            </span><br><br>
            <span>
              <label for="id_street" class="w150">Street:</label>
              <input id="id_street" name="street" type="text" required>
            </span><br><br>
            <span>
              <label for="id_house_number" class="w150">House number:</label>
              <input id="id_house_number" name="house_number" type="number" required>
            </span><br><br>
            <span>
              <label for="id_apartment_number" class="w150">Apartment number:</label>
              <input id="id_apartment_number" name="apartment_number" type="number">
            </span><br><br>
            <span>
              <label for="id_postal_code" class="w150">Postal code:</label>
              <input id="id_postal_code" name="postal_code" type="text" pattern="[0-9]{2}\-[0-9]{3}" required>
            </span><br><br>
            <span>
              <label for="id_city" class="w150">City:</label>
              <input id="id_city" name="city" type="text" required>
            </span><br><br>
          </div>
        </div>
        <button class="button form-button" type="submit">Add</button>
    {% endif %}
    </form>
  </div>
{% endblock %}

crmsite/templates/site/forms/user_form.html
{% extends "site/template.html" %}
{% block title %}Add User{% endblock %}
{% block content %}
  <div class="custom_form">
    <h3>Add new User</h3>
    <form action="{% url 'crmsite:save_user' %}" method="post">
      {% csrf_token %}
      <div>
        <div class="title-status">
          <span>
            <label for="id_name" class="w80">Username: </label>
            <input id="id_name" name="username" maxlength="100" type="text" autofocus required>
          </span><br><br>
          <span>
            <label for="id_first_name" class="w80">First name: </label>
            <input id="id_first_name" name="first_name" maxlength="100" type="text" required>
          </span><br><br>
          <span>
            <label for="id_last_name" class="w80">Last name: </label>
            <input id="id_last_name" name="last_name" maxlength="100" type="text" required>
          </span><br><br>
          <span>
            <label for="id_password" class="w80">Password: </label>
            <input id="id_password" name="password" maxlength="100" type="password" required>
          </span><br><br>
        </div>
      </div>
      <button class="button form-button" type="submit">Add</button>
    </form>
  </div>
{% endblock %}

crmsite/templates/site/lists/companies.html
{% extends "site/template.html" %}
{% block title %}Companies List{% endblock %}
{% block content %}
  <div class="object-title">
    <div>
      <h2>Companies List</h2>
    </div>
    <div class="control-panel">
      <a href="/crm/company/add/" class="btn btn-default">Create New Company</a>
    </div>
  </div>
  {% if companies %}
    <table id="sprint" class="table display cell-border">
      <thead>
        <tr>
          <th class="tableHeaderCell">Name</th>
        </tr>
      </thead>
      <tbody>
        {% for c in companies %}
          <tr>
            <td class="tableCell"><a href="/crm/company/{{ c.id }}"><div class="cell">{{ c.name }}</div></a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}

crmsite/templates/site/lists/users.html
{% extends "site/template.html" %}
{% block title %}Users List{% endblock %}
{% block content %}
  <div class="object-title">
    <div>
      <h2>Users List</h2>
    </div>
    <div class="control-panel">
      <a href="/crm/user/add/" class="btn btn-default">Create New User</a>
    </div>
  </div>
  {% if users %}
    <table id="sprint" class="table display cell-border">
      <thead>
        <tr>
          <th class="tableHeaderCell">Name</th>
          <th class="tableHeaderCell">Status</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for u in users %}
          <tr>
            <td class="tableCell">
              <div class="cell">
                {% if u.first_name and u.last_name %}
                  {{ u.first_name }} {{u.last_name}}
                {% else %}
                  {{ u.username }}
                {% endif %}
              </div>
            </td>
            <td class="tableCell"><div class="cell">{{ u.is_active }}</div></td>
            <td class="tableCell">
              <a href="/crm/user/{{ u.id }}/changestatus">
                <div class="cell">
                  {% if not u.is_staff %}
                    {% if u.is_active %}
                      <span class="glyphicon glyphicon-remove"></span>
                    {% else %}
                      <span class="glyphicon glyphicon-ok"></span>
                    {% endif %}
                  {% endif %}
                </div>
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}

crmsite/templates/site/template.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}CRM{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    <header class="container">
      <h1><span class="header_text">CRM</span></h1>
    </header>
    <main class="container">
      <nav class="navbar navbar-default" role="navigation">
        <ul class="nav navbar-nav">
          <li id="companies"><a href="/crm">Companies</a></li>
          <li id="users"><a href="/crm/users">Users</a></li>
        </ul>
        {% if user.is_authenticated %}
          <div class="btn-group navbar-right h50">
            <a class="btn dropdown-toggle menu" data-toggle="dropdown" href="#">
              <span><i class="fa fa-user"></i>&nbsp;{{ user.username }}</span>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
              <li id="logout"><a href="/crm/logout"><i class="fa fa-sign-out"></i>&nbsp;Logout</a></li>
            </ul>
          </div>
        {% endif %}
      </nav>
      <div id="content" class='content_container'>
        {% block content%}{% endblock %}
      </div>
    </main>
    <footer class="container">
      <div>
          Author: Paweł Mudlaff
      </div>
    </footer>
  </body>
</html>